/**
 * PDF Parser Utility
 * Handles parsing of PDF documents using pdf-lib to extract form fields and text content
 * Specifically designed for parsing accessibility testing PDFs generated by this application
 * 
 * @module PDFParser
 */

const { PDFDocument, PDFForm, PDFTextField, PDFCheckBox, PDFDropdown } = require('pdf-lib');
const fs = require('fs').promises;
const path = require('path');
const { createUploadLogger } = require('./pdf-logger');

const logger = createUploadLogger('PDFParser');

/**
 * PDF Parser Class
 * Provides utilities for loading and parsing PDF documents
 */
class PDFParser {
    constructor() {
        this.pdfDoc = null;
        this.form = null;
        this.pages = [];
        this.textContent = '';
        this.formFields = new Map();
        
        // Field name patterns for form extraction
        this.patterns = {
            // Overall requirement status checkboxes
            overallStatus: /^overall_status_(.+)$/,
            // Test instance status checkboxes (status_0_passed, status_1_failed, etc.)
            instanceStatus: /^status_(\d+)_(.+)$/,
            // Test instance notes text fields
            instanceNotes: /^notes_(\d+)$/,
            // Test instance results text fields (WYSIWYG content)
            instanceResults: /^results_(\d+)$/,
            // Test instance recommendations text fields (WYSIWYG content)
            instanceRecommendations: /^recommendations_(\d+)$/,
        };
        
        // Valid status values
        this.validStatuses = ['passed', 'failed', 'in_process', 'needs_review', 'not_applicable'];
    }
    
    /**
     * Load a PDF document from file path or buffer
     * @param {string|Buffer} source - File path or PDF buffer
     * @returns {Promise<PDFDocument>} Loaded PDF document
     */
    async loadPDF(source) {
        try {
            let pdfBytes;
            
            if (typeof source === 'string') {
                // Load from file path
                logger.info('📄 Loading PDF from file path', { filePath: source });
                pdfBytes = await fs.readFile(source);
            } else if (Buffer.isBuffer(source)) {
                // Use provided buffer
                logger.info('📄 Loading PDF from buffer', { bufferSize: source.length });
                pdfBytes = source;
            } else {
                throw new Error('Source must be a file path (string) or Buffer');
            }
            
            // Load the PDF document
            this.pdfDoc = await PDFDocument.load(pdfBytes);
            this.form = this.pdfDoc.getForm();
            this.pages = this.pdfDoc.getPages();
            
            logger.info('📄 PDF loaded successfully', {
                pageCount: this.pages.length,
                hasForm: !!this.form,
                formFieldCount: this.form ? this.form.getFields().length : 0
            });
            
            // Extract form fields
            await this.extractFormFields();
            
            // Extract text content
            await this.extractTextContent();
            
            return this.pdfDoc;
            
        } catch (error) {
            logger.error('❌ Failed to load PDF document', {
                error: error.message,
                stack: error.stack,
                sourceType: typeof source
            });
            throw new Error(`PDF loading failed: ${error.message}`);
        }
    }
    
    /**
     * Extract and catalog all form fields in the PDF
     * @private
     */
    async extractFormFields() {
        if (!this.form) {
            logger.warn('⚠️ No form found in PDF document');
            return;
        }
        
        try {
            const fields = this.form.getFields();
            logger.info('📋 Extracting form fields', { totalFields: fields.length });
            
            this.formFields.clear();
            
            for (const field of fields) {
                const fieldName = field.getName();
                const fieldType = field.constructor.name;
                let fieldValue = null;
                
                // Extract field value based on type
                try {
                    if (field instanceof PDFCheckBox) {
                        fieldValue = field.isChecked();
                    } else if (field instanceof PDFTextField) {
                        fieldValue = field.getText();
                    } else if (field instanceof PDFDropdown) {
                        fieldValue = field.getSelected();
                    } else {
                        // For other field types, try to get a generic value
                        fieldValue = field.getValue ? field.getValue() : null;
                    }
                } catch (fieldError) {
                    logger.warn('⚠️ Failed to extract value from field', {
                        fieldName,
                        fieldType,
                        error: fieldError.message
                    });
                }
                
                this.formFields.set(fieldName, {
                    name: fieldName,
                    type: fieldType,
                    value: fieldValue
                });
                
                logger.debug('📝 Form field extracted', {
                    name: fieldName,
                    type: fieldType,
                    value: fieldValue
                });
            }
            
            logger.info('✅ Form field extraction completed', { 
                extractedFields: this.formFields.size 
            });
            
        } catch (error) {
            logger.error('❌ Failed to extract form fields', {
                error: error.message,
                stack: error.stack
            });
            throw new Error(`Form field extraction failed: ${error.message}`);
        }
    }
    
    /**
     * Extract text content from all pages in the PDF
     * @private
     */
    async extractTextContent() {
        try {
            logger.info('📝 Extracting text content from PDF pages', { 
                pageCount: this.pages.length 
            });
            
            let combinedText = '';
            
            for (let i = 0; i < this.pages.length; i++) {
                const page = this.pages[i];
                
                try {
                    // Note: pdf-lib doesn't have built-in text extraction
                    // We'll focus on form fields for now, but this method
                    // can be extended with additional text extraction libraries
                    logger.debug('📄 Processing page for text extraction', { pageIndex: i });
                    
                    // For now, we'll rely on form field extraction
                    // and URL extraction from field values
                    
                } catch (pageError) {
                    logger.warn('⚠️ Failed to extract text from page', {
                        pageIndex: i,
                        error: pageError.message
                    });
                }
            }
            
            this.textContent = combinedText;
            
            logger.info('✅ Text content extraction completed', {
                textLength: this.textContent.length
            });
            
        } catch (error) {
            logger.error('❌ Failed to extract text content', {
                error: error.message,
                stack: error.stack
            });
            // Don't throw here - text extraction is not critical
            this.textContent = '';
        }
    }
    
    /**
     * Extract the overall requirement status from form fields
     * @returns {string|null} Status value (passed, failed, etc.) or null if not found
     */
    getOverallStatus() {
        try {
            logger.debug('🔍 Extracting overall status from form fields');
            
            for (const [fieldName, field] of this.formFields) {
                const match = fieldName.match(this.patterns.overallStatus);
                if (match && field.value === true) {
                    const status = match[1];
                    
                    // Validate status value
                    if (this.validStatuses.includes(status)) {
                        logger.info('✅ Overall status extracted', { status });
                        return status;
                    } else {
                        logger.warn('⚠️ Invalid status value found', { 
                            fieldName, 
                            status 
                        });
                    }
                }
            }
            
            logger.warn('⚠️ No overall status found in form fields');
            return null;
            
        } catch (error) {
            logger.error('❌ Failed to extract overall status', {
                error: error.message,
                stack: error.stack
            });
            return null;
        }
    }
    
    /**
     * Extract all test instance data from form fields
     * @returns {Array} Array of test instance objects
     */
    getTestInstances() {
        try {
            logger.debug('🔍 Extracting test instance data from form fields');
            
            const instances = new Map();
            
            // Process all form fields to extract test instance data
            for (const [fieldName, field] of this.formFields) {
                // Check for status fields
                const statusMatch = fieldName.match(this.patterns.instanceStatus);
                if (statusMatch && field.value === true) {
                    const index = parseInt(statusMatch[1], 10);
                    const status = statusMatch[2];
                    
                    if (this.validStatuses.includes(status)) {
                        if (!instances.has(index)) {
                            instances.set(index, { index });
                        }
                        instances.get(index).status = status;
                        
                        logger.debug('📝 Test instance status extracted', { 
                            index, 
                            status 
                        });
                    }
                }
                
                // Check for notes fields
                const notesMatch = fieldName.match(this.patterns.instanceNotes);
                if (notesMatch && field.value) {
                    const index = parseInt(notesMatch[1], 10);
                    
                    if (!instances.has(index)) {
                        instances.set(index, { index });
                    }
                    instances.get(index).notes = field.value;
                    
                    logger.debug('📝 Test instance notes extracted', { 
                        index, 
                        notesLength: field.value.length 
                    });
                }
                
                // Check for results fields (WYSIWYG content)
                const resultsMatch = fieldName.match(this.patterns.instanceResults);
                if (resultsMatch && field.value) {
                    const index = parseInt(resultsMatch[1], 10);
                    
                    if (!instances.has(index)) {
                        instances.set(index, { index });
                    }
                    instances.get(index).results = field.value;
                    
                    logger.debug('📝 Test instance results extracted', { 
                        index, 
                        resultsLength: field.value.length 
                    });
                }
                
                // Check for recommendations fields (WYSIWYG content)
                const recommendationsMatch = fieldName.match(this.patterns.instanceRecommendations);
                if (recommendationsMatch && field.value) {
                    const index = parseInt(recommendationsMatch[1], 10);
                    
                    if (!instances.has(index)) {
                        instances.set(index, { index });
                    }
                    instances.get(index).recommendations = field.value;
                    
                    logger.debug('📝 Test instance recommendations extracted', { 
                        index, 
                        recommendationsLength: field.value.length 
                    });
                }
            }
            
            // Convert map to sorted array
            const instanceArray = Array.from(instances.values()).sort((a, b) => a.index - b.index);
            
            logger.info('✅ Test instances extracted', { 
                instanceCount: instanceArray.length 
            });
            
            return instanceArray;
            
        } catch (error) {
            logger.error('❌ Failed to extract test instances', {
                error: error.message,
                stack: error.stack
            });
            return [];
        }
    }
    
    /**
     * Extract requirement number from text content or form fields
     * @returns {string|null} Requirement number (e.g., "1.1.1") or null if not found
     */
    getRequirementNumber() {
        try {
            logger.debug('🔍 Extracting requirement number');
            
            // First, try to extract from form field values
            for (const [fieldName, field] of this.formFields) {
                if (field.value && typeof field.value === 'string') {
                    // Look for WCAG criterion patterns like "1.1.1" or "2.4.3"
                    const wcagMatch = field.value.match(/\b(\d+\.\d+\.\d+)\b/);
                    if (wcagMatch) {
                        const requirement = wcagMatch[1];
                        logger.info('✅ Requirement number found in form field', { 
                            requirement, 
                            fieldName 
                        });
                        return requirement;
                    }
                }
            }
            
            // If not found in form fields, try text content (when available)
            if (this.textContent) {
                const wcagMatch = this.textContent.match(/\b(\d+\.\d+\.\d+)\b/);
                if (wcagMatch) {
                    const requirement = wcagMatch[1];
                    logger.info('✅ Requirement number found in text content', { 
                        requirement 
                    });
                    return requirement;
                }
            }
            
            logger.warn('⚠️ No requirement number found in PDF');
            return null;
            
        } catch (error) {
            logger.error('❌ Failed to extract requirement number', {
                error: error.message,
                stack: error.stack
            });
            return null;
        }
    }
    
    /**
     * Extract URLs from form field values
     * @returns {Array<string>} Array of extracted URLs
     */
    getURLs() {
        try {
            logger.debug('🔍 Extracting URLs from form fields');
            
            const urls = new Set(); // Use Set to avoid duplicates
            
            // Pattern to match URLs (basic URL detection)
            const urlPattern = /https?:\/\/[^\s]+/gi;
            
            // Also look for "URL: " prefix pattern as mentioned in PRD
            const urlPrefixPattern = /URL:\s*(https?:\/\/[^\s]+)/gi;
            
            for (const [fieldName, field] of this.formFields) {
                if (field.value && typeof field.value === 'string') {
                    // Check for URL prefix pattern first
                    let match;
                    while ((match = urlPrefixPattern.exec(field.value)) !== null) {
                        urls.add(match[1].trim());
                        logger.debug('📝 URL found with prefix', { 
                            url: match[1].trim(), 
                            fieldName 
                        });
                    }
                    
                    // Check for general URL pattern
                    urlPrefixPattern.lastIndex = 0; // Reset regex
                    while ((match = urlPattern.exec(field.value)) !== null) {
                        urls.add(match[0].trim());
                        logger.debug('📝 URL found', { 
                            url: match[0].trim(), 
                            fieldName 
                        });
                    }
                }
            }
            
            const urlArray = Array.from(urls);
            
            logger.info('✅ URLs extracted', { 
                urlCount: urlArray.length,
                urls: urlArray 
            });
            
            return urlArray;
            
        } catch (error) {
            logger.error('❌ Failed to extract URLs', {
                error: error.message,
                stack: error.stack
            });
            return [];
        }
    }
    
    /**
     * Get all form field names and their types for debugging
     * @returns {Array} Array of field info objects
     */
    getFormFieldInfo() {
        const fieldInfo = [];
        
        for (const [fieldName, field] of this.formFields) {
            fieldInfo.push({
                name: fieldName,
                type: field.type,
                hasValue: field.value !== null && field.value !== undefined,
                value: field.value
            });
        }
        
        return fieldInfo;
    }
    
    /**
     * Parse the entire PDF and return structured data
     * @returns {Object} Parsed PDF data structure
     */
    async parsePDF() {
        try {
            logger.info('🔍 Starting full PDF parsing');
            
            if (!this.pdfDoc) {
                throw new Error('No PDF document loaded. Call loadPDF() first.');
            }
            
            const parsedData = {
                requirement: {
                    number: this.getRequirementNumber(),
                    overallStatus: this.getOverallStatus()
                },
                testInstances: this.getTestInstances(),
                urls: this.getURLs(),
                metadata: {
                    pageCount: this.pages.length,
                    formFieldCount: this.formFields.size,
                    hasWYSIWYGFields: false,
                    extractedAt: new Date().toISOString()
                }
            };
            
            // Check if any WYSIWYG fields (results/recommendations) were found
            parsedData.metadata.hasWYSIWYGFields = parsedData.testInstances.some(
                instance => instance.results || instance.recommendations
            );
            
            logger.info('✅ PDF parsing completed', {
                requirementNumber: parsedData.requirement.number,
                overallStatus: parsedData.requirement.overallStatus,
                testInstanceCount: parsedData.testInstances.length,
                urlCount: parsedData.urls.length,
                hasWYSIWYGFields: parsedData.metadata.hasWYSIWYGFields
            });
            
            return parsedData;
            
        } catch (error) {
            logger.error('❌ PDF parsing failed', {
                error: error.message,
                stack: error.stack
            });
            throw new Error(`PDF parsing failed: ${error.message}`);
        }
    }
    
    /**
     * Cleanup resources
     */
    cleanup() {
        this.pdfDoc = null;
        this.form = null;
        this.pages = [];
        this.textContent = '';
        this.formFields.clear();
        
        try {
            logger.debug('🧹 PDF parser resources cleaned up');
        } catch (logError) {
            // Ignore logging errors during cleanup
            console.log('🧹 PDF parser resources cleaned up');
        }
    }
}

/**
 * Factory function to create a new PDF parser instance
 * @returns {PDFParser} New PDF parser instance
 */
function createPDFParser() {
    return new PDFParser();
}

/**
 * Utility function to parse a PDF file directly
 * @param {string|Buffer} source - File path or PDF buffer
 * @returns {Promise<Object>} Parsed PDF data
 */
async function parsePDFFile(source) {
    const parser = createPDFParser();
    
    try {
        await parser.loadPDF(source);
        const result = await parser.parsePDF();
        return result;
    } finally {
        parser.cleanup();
    }
}

module.exports = {
    PDFParser,
    createPDFParser,
    parsePDFFile
};
